### ISSUE TITLE
Error during make process

### ISSUE THREAD

**Issue by mjb32803** [enzo1982/BoCA#11]
Trying to learn more about how to build applications for source, so I tried to build fre:ac on my Ubuntu Mate 21.04 system.
Installed all the dependancies per the various readme files.
Think is successfully built and installed smoother-0.9.7 (didn't get any error messages after "make" and "make install")
Proceeded to build BoCA. Ran "make" and all seems to proceed fine until I get an Error message towards the end.
Here is the output from the "make" command. I'n not quite sure what I'm doing wrong.  I took a look at the file "common/metadata/picture.cpp" at line 31, 
Since I didn't get any error messages building Smooth, I'm not sure what's the root cause of the error?  
Any hints would be appreciated.  Thanks.

bakermj@Asus-Z170A:~/Downloads/BoCA-master$ sudo make install
cd include && make install && cd ..
make[1]: Entering directory '/home/bakermj/Downloads/BoCA-master/include'
install -d ""/usr/local/include
cp -r "/home/bakermj/Downloads/BoCA-master/include"/boca ""/usr/local/include
chmod -R a=rX,u=rwX ""/usr/local/include/boca
install -m 644 "/home/bakermj/Downloads/BoCA-master/include"/boca.h ""/usr/local/include
make[1]: Leaving directory '/home/bakermj/Downloads/BoCA-master/include'
cd runtime && make install && cd ..
make[1]: Entering directory '/home/bakermj/Downloads/BoCA-master/runtime'
mkdir -p application/external/posix
mkdir -p common/communication common/metadata component core
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/external/configlayer.cpp -o application/external/configlayer.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/external/decodercomponent.cpp -o application/external/decodercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/external/encodercomponent.cpp -o application/external/encodercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/component.cpp -o application/component.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/componentspecs.cpp -o application/componentspecs.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/decodercomponent.cpp -o application/decodercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/deviceinfocomponent.cpp -o application/deviceinfocomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/dspcomponent.cpp -o application/dspcomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/encodercomponent.cpp -o application/encodercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/extensioncomponent.cpp -o application/extensioncomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/outputcomponent.cpp -o application/outputcomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/playlistcomponent.cpp -o application/playlistcomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/registry.cpp -o application/registry.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/streamcomponent.cpp -o application/streamcomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/taggercomponent.cpp -o application/taggercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c application/verifiercomponent.cpp -o application/verifiercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/communication/application.cpp -o common/communication/application.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/communication/engine.cpp -o common/communication/engine.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/communication/joblist.cpp -o common/communication/joblist.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/communication/menu.cpp -o common/communication/menu.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/communication/settings.cpp -o common/communication/settings.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/metadata/device.cpp -o common/metadata/device.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/metadata/format.cpp -o common/metadata/format.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/metadata/info.cpp -o common/metadata/info.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/metadata/mcdi.cpp -o common/metadata/mcdi.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr/local\" -I"/home/bakermj/Downloads/BoCA-master/runtime"/../include -fPIC -pthread -I/usr/local/include  -c common/metadata/picture.cpp -o common/metadata/picture.o
common/metadata/picture.cpp: In member function ‘smooth::GUI::Bitmap BoCA::Picture::GetBitmap() const’:
common/metadata/picture.cpp:109:31: error: no matching function for call to ‘smooth::GUI::ImageLoader::Load(const BoCA::PictureData&)’
  109 |  return ImageLoader::Load(data);
      |                               ^
In file included from /usr/local/include/smooth.h:87,
                 from /home/bakermj/Downloads/BoCA-master/runtime/../include/boca/common/metadata/picturedata.h:16,
                 from /home/bakermj/Downloads/BoCA-master/runtime/../include/boca/common/metadata/picture.h:16,
                 from common/metadata/picture.cpp:13:
/usr/local/include/smooth/graphics/imageloader/imageloader.h:47:27: note: candidate: ‘virtual const smooth::GUI::Bitmap& smooth::GUI::ImageLoader::Load()’
   47 |     virtual const Bitmap &Load() = 0;
      |                           ^~~~
/usr/local/include/smooth/graphics/imageloader/imageloader.h:47:27: note:   candidate expects 0 arguments, 1 provided
/usr/local/include/smooth/graphics/imageloader/imageloader.h:49:21: note: candidate: ‘static smooth::GUI::Bitmap smooth::GUI::ImageLoader::Load(const smooth::String&)’
   49 |     static Bitmap   Load(const String &);
      |                     ^~~~
/usr/local/include/smooth/graphics/imageloader/imageloader.h:49:26: note:   no known conversion for argument 1 from ‘const BoCA::PictureData’ to ‘const smooth::String&’
   49 |     static Bitmap   Load(const String &);
      |                          ^~~~~~~~~~~~~~
/usr/local/include/smooth/graphics/imageloader/imageloader.h:50:21: note: candidate: ‘static smooth::GUI::Bitmap smooth::GUI::ImageLoader::Load(const smooth::Buffer<unsigned char>&, smooth::Short)’
   50 |     static Bitmap   Load(const Buffer<UnsignedByte> &, Short);
      |                     ^~~~
/usr/local/include/smooth/graphics/imageloader/imageloader.h:50:21: note:   candidate expects 2 arguments, 1 provided
make[1]: *** [Makefile:163: common/metadata/picture.o] Error 1
make[1]: Leaving directory '/home/bakermj/Downloads/BoCA-master/runtime'
make: *** [Makefile:28: install] Error 2
bakermj@Asus-Z170A:~/Downloads/BoCA-master$ ^C

**Comment by enzo1982** [comment]
As you are using BoCA-master, you should be using smooth-master as well, not the 0.9.7 release.

> common/metadata/picture.cpp:109:31: error: no matching function for call to ‘smooth::GUI::ImageLoader::Load(const BoCA::PictureData&)’
> 109 | return ImageLoader::Load(data);

There were some additions after smooth 0.9.7 to facilitate automatic image format detection. The `ImageLoader::Load` method now has a default argument for the second parameter, making the call in picture.cpp:109 valid.

**Comment by mjb32803** [comment]
Thanks for the help.  Problem solved. BoCA installed just fine.
