### ISSUE TITLE
Failing to build on linux due md5

### ISSUE THREAD

**Issue by andrecbarros** [enzo1982/BoCA#2]
Had to revert one of the changes from a couple of last updates.

See patch.

Regards,
André
[boca-md5-on-linux.patch.txt](https://github.com/enzo1982/BoCA/files/1644569/boca-md5-on-linux.patch.txt)

**Comment by enzo1982** [comment]
Oh, thanks! The MD5 line sneaked in prematurely.

I'll commit the full MD5 changes in an hour or so, then it should build fine again.

**Comment by enzo1982** [comment]
The changes are committed now.

When updating, make sure to also update fre:ac.
