### ISSUE TITLE
Bundles old vulnerable copy of uriparser 0.9.0, please update

### ISSUE THREAD

**Issue by hartwork** [enzo1982/BoCA#4]
Hi Robert,

it came to my attention that you bundle vulnerable uriparser 0.9.0 here. Please consider updating to [version 0.9.2](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.2). Thank you!

Best, Sebastian

**Comment by enzo1982** [comment]
Done. Thanks!

**Comment by hartwork** [comment]
That was quick, thank you!

289dc03fc1d08919b43a9e233f190ce6387b5e13
