### ISSUE TITLE
BoCa does not seem to compile under Ubuntu 16.04 - winegcc: gcc failed

### ISSUE THREAD

**Issue by mohi1978** [enzo1982/BoCA#6]
Hello enzo1982, I am interested in compiling freac to test it in my Laptop. Before that, I have followed the Readme nevertheless, compilations fails at this stage. Have you any clue of this kind of issue ?
Many thanks,
mohi1978

$ uname -a
Linux cdefigueiredo-HP-EliteBook-840-G2 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

make[4] : on entre dans le répertoire « /home/cdefigueiredo/Dev/Tools/BoCA/components/encoder/coreaudioconnect/connector »
winegcc -Wno-multichar -I/home/cdefigueiredo/Dev/Tools/BoCA/components/encoder/coreaudioconnect/connector -I ../../../../include -DUNICODE  -c dllinterface.cpp -o dllinterface.o
In file included from dllinterface.cpp:13:0:
dllinterface.h:13:21: fatal error: windows.h: Aucun fichier ou dossier de ce type
compilation terminated.
winegcc: gcc failed
Makefile:41 : la recette pour la cible « dllinterface.o » a échouée
make[4]: *** [dllinterface.o] Erreur 2
make[4] : on quitte le répertoire « /home/cdefigueiredo/Dev/Tools/BoCA/components/encoder/coreaudioconnect/connector »
../../../Makefile-commands:49 : la recette pour la cible « allcmds » a échouée
make[3]: *** [allcmds] Erreur 2
make[3] : on quitte le répertoire « /home/cdefigueiredo/Dev/Tools/BoCA/components/encoder/coreaudioconnect »
Makefile:32 : la recette pour la cible « coreaudioconnect » a échouée
make[2]: *** [coreaudioconnect] Erreur 2
make[2] : on quitte le répertoire « /home/cdefigueiredo/Dev/Tools/BoCA/components/encoder »
Makefile:14 : la recette pour la cible « encoder » a échouée
make[1]: *** [encoder] Erreur 2
make[1] : on quitte le répertoire « /home/cdefigueiredo/Dev/Tools/BoCA/components »
Makefile:8 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by enzo1982** [comment]
The build system is looking for `winegcc` and tries to build the Core Audio Connector component if it is found.

On your system, it seems that `winegcc` is there, but somehow other components of the Wine development ecosystem are missing.

You can skip building the Core Audio Connector by running `make USE_WINE=False`.
