### ISSUE TITLE
Can't build BoCa 1.0 package from AUR

### ISSUE THREAD

**Issue by DarkSwan86** [enzo1982/BoCA#7]
Hi @enzo1982 !

I'm trying to build Boca 1.0 from AUR (for freac 1.1), i have all the dependencies installed and i've also compiled smooth 0.9.4 correctly from AUR. The problem is that doesn't compile correctly and abort with this error:

==> Avvio di build() in corso...
mkdir -p ./bin ./lib
cd runtime && make  && cd ..
make[1]: ingresso nella directory «/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime»
mkdir -p application/external/posix
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr\" -I"/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime"/../include -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -c application/external/configlayer.cpp -o application/external/configlayer.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr\" -I"/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime"/../include -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -c application/external/decodercomponent.cpp -o application/external/decodercomponent.o
mkdir -p common/communication common/metadata component core
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr\" -I"/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime"/../include -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -c application/external/encodercomponent.cpp -o application/external/encodercomponent.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr\" -I"/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime"/../include -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -c application/component.cpp -o application/component.o
g++ -fvisibility=hidden -DBOCA_CDK_BUILD -DBOCA_INSTALL_PREFIX=\"/usr\" -I"/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime"/../include -fPIC -pthread -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -c application/componentspecs.cpp -o application/componentspecs.o
application/external/configlayer.cpp: In constructor ‘BoCA::AS::ConfigLayerExternal::ConfigLayerExternal(BoCA::AS::ComponentSpecs*)’:
application/external/configlayer.cpp:31:59: error: no matching function for call to ‘smooth::GUI::EditBox::EditBox(smooth::GUI::Point, smooth::GUI::Size)’
   31 |  edit_commandline = new EditBox(Point(6, 26), Size(400, 0));
      |                                                           ^
In file included from /usr/local/include/smooth.h:130,
                 from /var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime/../include/boca/application/external/../../common/configlayer.h:16,
                 from /var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime/../include/boca/application/external/configlayer.h:16,
                 from application/external/configlayer.cpp:13:
/usr/local/include/smooth/gui/widgets/basic/editbox.h:46:10: note: candidate: ‘smooth::GUI::EditBox::EditBox(const smooth::String&, const smooth::GUI::Point&, const smooth::GUI::Size&, smooth::Int)’
   46 |          EditBox(const String &, const Point &, const Size &, Int = 0);
      |          ^~~~~~~
/usr/local/include/smooth/gui/widgets/basic/editbox.h:46:10: note:   candidate expects 4 arguments, 2 provided
/usr/local/include/smooth/gui/widgets/basic/editbox.h:36:19: note: candidate: ‘smooth::GUI::EditBox::EditBox(const smooth::GUI::EditBox&)’
   36 |   class SMOOTHAPI EditBox : public Widget
      |                   ^~~~~~~
/usr/local/include/smooth/gui/widgets/basic/editbox.h:36:19: note:   candidate expects 1 argument, 2 provided
make[1]: *** [Makefile:163: application/external/configlayer.o] Errore 1
make[1]: *** Attesa per i processi non terminati....
make[1]: uscita dalla directory «/var/tmp/pamac-build-leonardo/boca/src/BoCA-1.0/runtime»
make: *** [Makefile:9: all] Errore 2
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

I'm missing something obvious here? I'm using Manjaro as distribution.

Thanks for the help and the fantastic work on Freac!

**Comment by enzo1982** [comment]
Hi, the compiler finds smooth header files in /usr/local/include and those appear to be pre-0.9 headers.

Not sure where you installed smooth 0.9.4, but presumably the headers are in /usr/include. You need to uninstall you local copy of smooth 0.8.*. If you are unsure, removing the following files should be sufficient:

rm -fr /usr/local/include/smooth*
rm -f /usr/local/lib/libsmooth*
rm -f /usr/local/bin/smooth-translator

**Comment by DarkSwan86** [comment]
Hi @enzo1982 ,

It worked! Now Boca builds correctly! Thanks!
